### PR TITLE
fixed cron syntax

### PR DESCRIPTION
**Pull request by SubhrajitPrusty**
#6 fixed issue in this pull

### CODE REVIEW

**Comment by zorroblue** [comment]
Nopes :stuck_out_tongue:  I think this will run only on the 1st of every month, infact every minute on that day.
Have a look at https://stackoverflow.com/questions/3984134/how-to-write-a-cron-that-will-run-a-script-every-day-at-midnight.

**Comment by SubhrajitPrusty** [comment]
updated

**Comment by zorroblue** [comment]
@SubhrajitPrusty  Looks good. Can you squash the three commits into one using git rebase? I'll merge it once it's done

**Comment by SubhrajitPrusty** [comment]
Okay, done.

**Comment by zorroblue** [comment]
Thanks!

**Pull request merged**
